name: Build and Release LaTeX

on:
  push:
    branches:
      - master
  workflow_dispatch: # allows manual triggering
  pull_request:

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: xu-cheng/texlive-action@v3
        with:
          root_file: main.tex"

      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: |
            main.pdf
          retention-days: 5
