name: Build and Release LaTeX

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch: # allows manual triggering

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -jobname=main

      - name: Rename PDF
        id: rename-pdf
        run: |
          echo "Renaming PDF"
          # read tag name and extract the name after last dot
          tag_name=$(echo $GITHUB_REF | cut -d'.' -f3)
          file_name=Mansour_MAHBOUBI_${tag_name}.pdf
          mv main.pdf "${file_name}"
          # store file name to be used in the next steps
          echo "file_name=${file_name}" >> $GITHUB_OUTPUT

      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: ${{ steps.rename-pdf.outputs.file_name }}
          retention-days: 1

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ steps.rename-pdf.outputs.file_name }}
